name: BDD Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container: python:3.9-slim

    # Required services    
    services:
      # Label used to access the service container
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test
        ports:
          - 5432:5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y curl wget python3-selenium

      - name: Install packages
        run: |
          python -m pip install --upgrade pip wheel
          pip install -r requirements.txt

      - name: Run the server locally
        run: |
          psql -c 'create database test;' -U postgres
        # Update the chromedriver to the latest version, otherwise it would not be compatible with Chrome v92
          LATEST_CHROMEDRIVER_VERSION=`curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE"`
          curl "https://chromedriver.storage.googleapis.com/${LATEST_CHROMEDRIVER_VERSION}/chromedriver_linux64.zip" -O
          unzip chromedriver_linux64.zip -d ~/bin
          chromedriver --version
          gunicorn --log-level=critical --bind=127.0.0.1:5000 service:app &  # start a Web server in the background
          sleep 5 # give Web server some time to bind to sockets, etc
          curl -I http://localhost:5000/  # make sure the service is up
          echo "\n*** SERVER IS RUNNING ***"
        
      - name: Run unit tests with behave
        run: behave
  